name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v4

    # Fix APT mirrors & install dependencies safely
    - name: Install dependencies (curl, wget, libssl1.1, Java)
      run: |
        sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.edge.kernel.org/ubuntu/|g' /etc/apt/sources.list
        apt-get clean
        apt-get update --fix-missing
        apt-get install -y --fix-missing curl wget libssl1.1 openjdk-11-jre publicsuffix

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.0.x

    - name: Embold Analyse
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"

        curl --silent --location --request GET \
        "${{ vars.EMBOLD_URL_CS }}/api/v1/repositories/841e052c7d355a559e07e37d927d10e5/scans/config/download" \
        --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" \
        -o repository-configuration.json

        echo "Download repository configuration file done"

        ./browserstack-codequality-scanner/bin/embold-scanner analyse \
          -u ${{ vars.EMBOLD_URL_CS }} \
          -t ${{ secrets.EMBOLD_TOKEN_CS}} \
          -r 841e052c7d355a559e07e37d927d10e5 \
          -b . \
          -d ./embold-data \
          -c ./repository-configuration.json \
          -l ./embold-log \
          -sh $GITHUB_WORKSPACE/embold-scanner-home \
          -v
